image: php:5.6
before_script:
  - set -xe
  - apt-get update -yqq
  - apt-get install -yqq lftp
stages:
  - build
  - deploy
build:
  stage: build
  script: 
    - cp -R src/ dist/
  artifacts:
    paths:
      - dist/
  only:
    - master
  tags:
    - docker
deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - lftp -e "mirror --no-perms --exclude-glob .git* --exclude .git/ -R dist/ /" -u cv.gregory.anne,$FTP_PASSWORD ftpperso.free.fr
  only:
    - master
  tags:
    - docker