image: php:5.6
cache:
  paths:
  - vendor
before_script:
  - set -xe
  - apt-get update -yqq
stages:
  - build
  - deploy
build:
  stage: build
  script: 
    - apt-get install -yqq zip unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
    - cp -R src/ dist/
    - cp -R vendor/ dist/version-1/php/vendor/
  artifacts:
    paths:
      - dist/
  only:
    - master
  tags:
    - docker
deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - apt-get install -yqq lftp
    - mkdir ~/.lftp
    - echo "set ssl:verify-certificate no" > ~/.lftp/rc
    - lftp -e "mirror --no-perms --exclude-glob .git* --exclude .git/ -R dist/ /" -u unaux_27147990,$PROFREEHOST_FTP_PASSWORD ftpupload.net
  only:
    - master
  tags:
    - docker