image: php:5.6
before_script:
  - set -xe
  - apt-get update -yqq
  - apt-get install -yqq git
  - apt-get install -yqq lftp
stages:
  - deploy
deploy:
  stage: deploy
  script: 
    - lftp -c "open -u cv.gregory.anne,$FTP_PASSWORD ftpperso.free.fr; mirror -Rnev --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
  only:
    - master
  tags:
    - docker