image: php:5.6
before_script:
  - set -xe
  - apt-get update -yqq
  - apt-get install -yqq lftp wget
  - echo "deb http://packages.dotdeb.org wheezy-php56 all" >> /etc/apt/sources.list
  - echo "deb-src http://packages.dotdeb.org wheezy-php56 all" >> /etc/apt/sources.list
  - wget https://www.dotdeb.org/dotdeb.gpg
  - apt-key add dotdeb.gpg
  - apt-get update -yqq
  #- apt-get install -yqq zip unzip php5.6-zip
  - apt-get install -yqq zip unzip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
stages:
  - build
  - deploy
build:
  stage: build
  script: 
    - cp -R src/ dist/
    - cd dist/version-1/php
    - composer install
    - cd ../../..
  artifacts:
    paths:
      - dist/
  only:
    - master
  tags:
    - docker
deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - lftp -e "mirror --no-perms --exclude-glob .git* --exclude .git/ -R dist/ /" -u cv.gregory.anne,$FTP_PASSWORD ftpperso.free.fr
  only:
    - master
  tags:
    - docker